name: Update translations

on:
  workflow_dispatch:

jobs:
  update-translations:
    runs-on: ubuntu-latest
    
    env:
      ACTION_REPOSITORY: ${{ github.action_repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: echo "$ACTION_REPOSITORY"
