name: Update translations

on:
  workflow_dispatch:

jobs:
  update-translations:
    runs-on: ubuntu-latest
    
    env:
      ACTION_REPOSITORY: ${{ github.action_repository }}

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo $ACTION_REPOSITORY
