name: Update translations

on:
  workflow_dispatch:

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update translations
        run: |
          curl -X GET "https://factorio-mods-localization.fly.dev/api/triggerUpdate?repo=${{ github.repository }}"
